config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'places#home' # get (reading) loads website
  get '/' => 'places#home'
  get '/place/new' => 'places#new'
  post '/place' => 'places#create' # post (writing) gdy formularz ma akcję /place i ją wykonamy, wowczas
  # zostaniemy przeniesieni do controllera places, metody create.
  # formularze zawsze tworza akcje post albo put (tylko do tworzenia rzeczy)
  get '/dinoplaces' => 'places#dinoplaces'
  get '/map' => 'places#map'
  get '/about' => 'places#about'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  has_attached_file :image, styles: { small: "64x64", med: "280x280", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  # this file works only on server. The content of this file will
  # not be visible on the website.
  def home
  end

  def dinoplaces # is used in dinoplaces.html.erb file
    @places = Place.all # takes all objects from table place in database
  end

  def map
  end

  def about
  end

  def new # is used in new.html.erb file
    @place = Place.new # prepares a new container for a new object
  end # nothing happens in database - we add new place in create method below

  def create
    @place = Place.new(place_params)
    if place_params[:user_name].length > 0 && place_params[:name].length > 0 && place_params[:description].length > 1 && place_params[:address].length > 1 then
    	if @place.save # if place is saved = created (click create) and saved in DB
        flash[:notice] = "----- A new dino has been created by < #{place_params[:user_name]} > -----"
        redirect_to '/dinoplaces'
    	else
        @form_error = true
      	render 'place/new' # render new page again, no changes on server/database (refresh)
    	end
    else
      flash[:notice] = "You haven't provided enough information to add a new dinosaur."
      render 'new' #render new.html.erb view
    end
  end

private
  def place_params
    params.require(:place).permit(:user_name, :name, :description, :address, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		 <%= stylesheet_link_tag "home_style" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>
		<div class="top-menu">  <!-- ________________________________________TOP MENU______________________________________ -->
			<nav class="navigation">
 			 	<ul>
					<a href="#" id="top"><li>BEST DINOS</li></a>
					 <a href="#" id="top"><li>MAP</li></a>
					 <a href="#" id="top"><li>DINO DATABASE</li></a>
					 <a href="#" id="top"><li>ADD A DINO</li></a>
					 <a href="#" id="top"><li>CONTACT</li></a>
  			</ul>
			</nav>
		</div>
		<div class="intro">
			<div class ="dinosaur_Q_and_A">
				<h1> Why dinosaurs in London? </h1>
				<p1> Because London is full of dinosaurs. <br>
				You can find them in museus and galleries, <br>
				but also in pubs, underground and shops. <br><br>
				This website collects them all. <br> </p1>
			</div>
		</div>
		<div class="slides">
			<div class="phenomenon_description">
				<div class="description_text">
					<p4> See the best dinosaurs in London <br> </p4>
				</div>
			</div>
		</div>
		<div class="dinosaur_map_invit">
			<p4> See the map of all London dinosaurs </p4>
		</div>
		<div class="dinosaur_map">
		</div>
		<div class ="dinosaur_database">
			<p4> Check our full dino-database </p4>
		</div>
		<div class ="dinosaur_grid">
			<!-- opening tag and percent below means that we use ruby here [does operation]-->
			<% @places.each do |place| %>
				<div class="dino_box">
					<!-- opening tag, percent and assignment below means that we use ruby here [does operation and returns value]-->
					<h2> <%= place.name %>  </h2> <br>
					<p2> <%= place.description %> </p2> <br>
					<p3> <%= place.address %> </p3> <br><br>
					<img src=<%= place.image %> height="250px" width="250px" class="dinopic">
				</div>
			<% end %>
		</div>
		<div class ="dinosaur_add_invit">
			<p4> Add a dinosaur to our website </p4>
		</div>
		<div class="add_a_dinosaur">
			<p6> 1) Fill a form - provide us with: </p6>
			    <p7> > title of image <br>
					 > description of the image <br>
					 > address of the dinosaur <br>
					 > and link to image  <br> </p7>
			   <p6>
					2) Add a dinosaur by clicking the button below. </p6> <br><br>
					 <p8>Remember - once added, the dinosaur info cannot be removed.</p8>
			<div class ="button"><%= link_to 'New Dino Place', "home/new" %></div>
		</div>
	</body>
</html>

app/views/pages/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		 <%= stylesheet_link_tag "new_style" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>
		<div class="top-menu">  <!-- ________________________________________TOP MENU______________________________________ -->
			<nav class="navigation">
 			 	<ul>
					<a href="#" id="top"><li>BEST DINOS</li></a>
				 	 <a href="#" id="top"><li>MAP</li></a>
				 	 <a href="#" id="top"><li>DINO DATABASE</li></a>
				 	 <a href="#" id="top"><li>ADD A DINO</li></a>
				 	 <a href="#" id="top"><li>CONTACT</li></a>
  			</ul>
			</nav>
		</div>
    <div class="create">
      <div class="container">
       	<%= form_for(@place) do |f| %>
      		<div class="field">
        		<%= f.label :place %><br>
        		<%= f.text_area :name %>
            <%= f.text_area :description %>
            <%= f.text_area :address %>
            <%= f.text_area :image %>
      		</div>
      		<div class="actions">
        		<%= f.submit "Create" %>
      		</div>
    		<% end %>
      </div>
    </div>


      </div>
    </div>
</body>
</html>

app/views/places/about.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="https://vignette.wikia.nocookie.net/dino/images/5/56/9540143_orig.png/revision/latest?cb=20150912162803">
	<!-- Required meta tags -->
	 <meta charset="utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	 <!-- Bootstrap CSS-->
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag "general_css" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>

	<!-- BOOTSTRAP NAVBAR -->

			<nav class="navbar navbar-expand-sm sticky-top navbar-light bg-light">
				<a class="navbar-brand" href="/home"><img src="http://icons.veryicon.com/256/System/Line/Dinosaur.png" height="50em"></a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarNav">
			    <ul class="navbar-nav">
			      <li class="nav-item">
			        <a class="nav-link" href="/map">MAP </a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/dinoplaces">DINO DATABASE</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="place/new">ADD A DINO</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/about">ABOUT</a>
			      </li>
			    </ul>
			  </div>
			</nav>

    <div class="subsite_header">
      <p4> ABOUT </p4>
    </div>
    <div class="website_info">
      <div class="about_us">
        <p10> This website has been build by <a href="https://github.com/Kotauror"><img src="https://image.flaticon.com/icons/svg/25/25231.svg" height=25px, class="cat"></a>
          Kotauror. <br><br>
          At the beginning, this website served coding training purposes,
          but then I've decided to keep it for the glory of London Dinosaurs
          and dinosaur-lovers community. </p10>
     </div>
    </div>
		<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  </body>
  </html>

app/views/places/dinoplaces.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="https://vignette.wikia.nocookie.net/dino/images/5/56/9540143_orig.png/revision/latest?cb=20150912162803">
		<!-- Required meta tags -->
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		 <!-- Bootstrap CSS-->
		 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
		 <%= stylesheet_link_tag "dinoplaces_style" %>
     <%= stylesheet_link_tag "general_css" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>

		<!-- BOOTSTRAP NAVBAR -->
				<nav class="navbar navbar-expand-sm sticky-top navbar-light bg-light" class="nav">
					<a class="navbar-brand" href="/home"><img src="http://icons.veryicon.com/256/System/Line/Dinosaur.png" height="50em"></a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="navbarNav">
				    <ul class="navbar-nav">
				      <li class="nav-item">
				        <a class="nav-link" href="/map">MAP </a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="/dinoplaces">DINO DATABASE</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="place/new">ADD A DINO</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="/about">ABOUT</a>
				      </li>
				    </ul>
				  </div>
				</nav>


		<div class ="subsite_header">
			<p4> Dino-database </p4>
		</div>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
		<div class = "site">
		<div class ="dinosaur_grid">
			<!-- opening tag and percent below means that we use ruby here [does operation]-->
			<% @places.each do |place| %>
				<div class="dino_box">
					<!-- opening tag, percent and assignment below means that we use ruby here [does operation and returns value]-->
					<h2> <%= place.name.upcase %>  </h2>
					<br>
        	<div class="small_image">
						<%= link_to image_tag(place.image.url(:med)), place.image.url %>
					</div>
					<br>
        	<p3> Added by: <%= place.user_name %> </p3>
					<br>
					<p2> Description: <%= place.description %> </p2>
					<br>
					<p2> Address: <%= place.address %> </p2>
					<br>
					<p2> Created: <%= place.created_at %> </p3>
					<br>
				</div>
			<% end %>
		</div>
	</div>

</html>

app/views/places/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="https://vignette.wikia.nocookie.net/dino/images/5/56/9540143_orig.png/revision/latest?cb=20150912162803">
		<!-- Required meta tags -->
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		 <!-- Bootstrap CSS-->
		 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
		 <%= stylesheet_link_tag "home_style" %>
		 <%= stylesheet_link_tag "general_css" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>

<!-- BOOTSTRAP NAVBAR -->

		<nav class="navbar navbar-expand-sm sticky-top navbar-light bg-light">
		  <a class="navbar-brand" href="/home"><img src="http://icons.veryicon.com/256/System/Line/Dinosaur.png" height="50em"></a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="/map">MAP</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/dinoplaces">DINO DATABASE</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="place/new">ADD A DINO</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/about">ABOUT</a>
		      </li>
		    </ul>
		  </div>
		</nav>

		<div class="intro">
			<div class ="dinosaur_Q_and_A">
				<h1>  Dinosaurs in London. </h1>
				<p1> Because London is full of dinosaurs. <br>
				You can find them in museums and galleries, <br>
				but also in pubs, underground and shops. <br><br>
				This website collects them all <br>
				and allows you to add your dino to our database!
				</p1>
			</div>
			<div class="sir"><img src="https://image.ibb.co/m71Mj6/like_a_sir.png", height=200px, id="sir"></div>
		</div>
		<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
	</body>
</html>

app/views/places/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="https://vignette.wikia.nocookie.net/dino/images/5/56/9540143_orig.png/revision/latest?cb=20150912162803">
		<!-- Required meta tags -->
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		 <!-- Bootstrap CSS-->
		 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
		 <%= stylesheet_link_tag "new_style" %>
		 <%= stylesheet_link_tag "general_css" %>
    	<title>London dinosaurs</title>
		<script src="https://use.fontawesome.com/b6e46f96f4.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
	</head>
	<body>


<!-- BOOTSTRAP NAVBAR -->
		<nav class="navbar navbar-expand-sm sticky-top navbar-light bg-light">
			<a class="navbar-brand" href="/home"><img src="http://icons.veryicon.com/256/System/Line/Dinosaur.png" height="50em"></a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="/map">MAP </a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/dinoplaces">DINO DATABASE</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="place/new">ADD A DINO</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/about">ABOUT</a>
		      </li>
		    </ul>
		  </div>
		</nav>


		<div class ="subsite_header">
			<p4> Add a dinosaur </p4>
		</div>
		<% if flash[:notice] %>
			<div class="notice"><%= flash[:notice] %></div>
		<% end %>

    <div class="create">
			<% if @form_error == true %>
				<div class="wrong_form">
					There was a missing info in the form
				</div>
			<% end %>



	    <%= form_for @place, url: '/place', html: { multipart: true } do |f| %>
    		<div class="fields">
					<p7> Your name: * <br> <%= f.text_area :user_name, class: "single_field", placeholder: "What's your name?" %> </p7>
      		<p7> Dinosaur name: * <br> <%= f.text_area :name, class: "single_field", placeholder: "How do you want to name this dinosaur?" %> </p7>
          <p7> Description: * <br> <%= f.text_area :description, class: "single_field", placeholder: "Add a brief description of this dinosaur." %> </p7>
          <p7> Address: * <br> <%= f.text_area :address, class: "single_field", placeholder: "Where can we find this dinosaur?" %> </p7><br>
					<p8> * - mandatory fields </p8>
					<br>
					<form>
			  	<div class="form-group">
				    <p7> Upload an image from a file: </p7><br>
						<div class="upload"><%= f.file_field :image %></div>
			  	</div>
    		</div>
    		<div class="actions">
      		<%= f.submit "Submit", class: "button" %> <!-- when submit is called, take data from form and send them to url: place_path-->
    		</div><br>
				<p8>Remember - once added, the dinosaur info cannot be removed.</p8>
				<p8>At least not by you.</p8>
  		<% end %>
			<img src="https://i0.wp.com/islanublar.jurassicworld.com/media/dinosaurs/apatosaurus/apatosaurus-info-graphic.png", id="bronto">
  	</div>


		<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>